import '../styles.css'

const Services = () => {
  return (
    <div className='text'>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.
      <br /><br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.
      <br /><br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.
     <br /><br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.
      <br /><br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.
      <br /><br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.
      <br /><br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam architecto aspernatur aliquam sed accusantium quae temporibus fuga neque dolorem, fugit explicabo deleniti dolor incidunt eos et, consequuntur, repellendus animi dolore.
     
    </div>
  )
}

export default Services
